DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS provinces CASCADE;
DROP TABLE IF EXISTS salaries CASCADE;
DROP TABLE IF EXISTS deductions CASCADE;
DROP TABLE IF EXISTS rates CASCADE;


CREATE TABLE provinces(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE deductions(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE users(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  province_id INTEGER REFERENCES provinces(id) ON DELETE CASCADE,
  salary BIGINT,
  deductions_id INTEGER REFERENCES deductions(id) ON DELETE CASCADE
);

CREATE TABLE rates(
  id SERIAL PRIMARY KEY NOT NULL,
  rate DECIMAL NOT NULL
);

CREATE TABLE salaries(
  id SERIAL PRIMARY KEY NOT NULL,
  province_id INTEGER REFERENCES provinces(id) ON DELETE CASCADE,
  rate_id INTEGER REFERENCES rates(id) ON DELETE CASCADE,
  salary BIGINT NOT NULL
);


